name: spac
channels:
  - ohsu-comp-bio
  - conda-forge
  - leej3
  - https://fnlcr-dmap.github.io/scimap/
dependencies:
  - python=3.9.13               # Core Python Package
  - numpy=1.26.4                # Core Python Package
  - pandas=1.5.3                # Data Manipulation and Analysis
  - anndata=0.10.9              # Single-Cell Data Manipulation and Analysis (scverse family)
  - scimap=2.1.3_dmap_pandas153 # Single-Cell Data Data Manipulation and Analysis
  - scanpy=1.10.3               # Single-Cell Data Manipulation and Analysis (scverse family)
  - zarr=2.10.3                 # Data Manipulation and Analysis
  - numba=0.58.1                # Data Manipulation and Analysis
  - phenograph=1.5.7            # Data Manipulation and Analysis
  - scikit-learn=1.5.2          # Machine Learning and Statistics
  - matplotlib=3.9.2            # Visualization and Plotting
  - seaborn=0.13.2              # Visualization and Plotting
  - datashader=0.16.3           # Visualization and Plotting
  - plotly=5.24.1               # Visualization and Plotting
  - squidpy=1.2.2               # Single-Cell Visualization and Plotting (scverse family)
  - pillow=11.0.0               # Image Processing
  - python-kaleido=0.2.1        # Image Processing
  - jupyter                     # Notebook Environment
  - scipy=1.12.0                # Statistics (constrained by scimap)
  - dask=2023.12.1              # Parallel Computing (constrained by scimap)
  - tifffile=2023.9.26          # Image I/O (constrained by scimap)
  - mpl-scatter-density=0.7     # Visualization (constrained by scimap)
  - pip:
    - pylint
    - pytest==7.4.4             # Testing (constrained by scimap)
    - sphinx
    - flake8
    - gendocs
    - parmap==1.7.0
    - combat==0.3.3             # Batch correction (required by scimap)
    - scimap
